apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-express-app
  template:
    metadata:
      labels:
        app: node-express-app
    spec:
      containers:
        - name: node-express-app
          image: <YOUR_ECR_REPOSITORY_URL>/node-express-app:latest
          ports:
            - containerPort: 3000
          # Example of passing an environment variable (optional)
          env:
            - name: PORT
              value: "3000"